name: check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      WIREIT_LOGGER: metrics
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - run: pnpm ci
      - run: pnpm run rbuild
      - run: pnpm run rcheck
      - run: pnpm exec playwright install chromium --with-deps
      - run: pnpm run rtest
