name: check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DO_NOT_TRACK: 1
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - run: pnpm ci
      - run: pnpm run build
      - run: pnpm run check
      - run: pnpm exec playwright install chromium --with-deps
      - run: pnpm run test
